import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
           <p>&nbsp;</p><div class="separator" style="clear: both; text-align: center;"><a href="https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjIOKTWh0K-KGJ33VnIpJdG9Zip5Emj8Fr6NfvhxGJH1B-MlBlWGsUKh9Mz8LVVrF2V0LbeSzYEjtvTI2j9v98Qyi1dl6D4DP5IN_JZajYmfcaO9_iizsFDCpTeukeypwX2MzYCzIJbYacpBNAr0lf8bRPAhPGAaVEnZFpzkB7WUSklscwHuiYcFM-55g/s300/Make%20a%20grand%20during%20Mardi%20Gras%20St.%20Louis%20homeowner%20lists%20Soulard%20Airbnb%20for%20$1,000%20a%20night!.jpeg" imageanchor="1" style="margin-left: 1em; margin-right: 1em;"><img alt="Make a grand during Mardi Gras St. Louis homeowner lists Soulard Airbnb for $1,000 a night!" border="0" data-original-height="168" data-original-width="300" src="https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjIOKTWh0K-KGJ33VnIpJdG9Zip5Emj8Fr6NfvhxGJH1B-MlBlWGsUKh9Mz8LVVrF2V0LbeSzYEjtvTI2j9v98Qyi1dl6D4DP5IN_JZajYmfcaO9_iizsFDCpTeukeypwX2MzYCzIJbYacpBNAr0lf8bRPAhPGAaVEnZFpzkB7WUSklscwHuiYcFM-55g/s16000/Make%20a%20grand%20during%20Mardi%20Gras%20St.%20Louis%20homeowner%20lists%20Soulard%20Airbnb%20for%20$1,000%20a%20night!.jpeg" title="Make a grand during Mardi Gras St. Louis homeowner lists Soulard Airbnb for $1,000 a night!" /></a></div><br /><p></p><p>A St. Louis man has listed his Soulard home on Airbnb for a whopping $1,000 a night during Mardi Gras weekend. The four-bedroom, two-bathroom house is located just blocks from the parade route and is being marketed as a prime location for a group of friends looking to enjoy the festivities.</p><p><br /></p><p>While the price tag may seem steep, the homeowner says he has already received interest from several potential renters. He also notes that the high price is in line with other listings in the area, which are in high demand during Mardi Gras weekend.</p><p><br /></p><p>This isn't the first time that St. Louis residents have taken advantage of the city's Mardi Gras celebrations to make a little extra cash. In fact, many homeowners in the Soulard neighborhood have been renting out their homes during the annual event for several years.</p><p><br /></p><p>While the extra income can be tempting, homeowners should be aware of the potential risks of renting out their homes, such as property damage or liability issues. It's important to have the proper insurance and to thoroughly vet potential renters before agreeing to a rental arrangement.</p><p><br /></p><p>Overall, renting out a home on Airbnb during Mardi Gras weekend can be a lucrative opportunity for homeowners in the Soulard area. However, it's important to weigh the potential risks and take the necessary precautions to protect your property and your financial interests.</p>
          </p>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{' '}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
        </div>

        <div className={styles.grid}>
          <a
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Docs <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Find in-depth information about Next.js features and&nbsp;API.
            </p>
          </a>

          <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Learn <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Learn about Next.js in an interactive course with&nbsp;quizzes!
            </p>
          </a>

          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Templates <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Discover and deploy boilerplate example Next.js&nbsp;projects.
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Deploy <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Instantly deploy your Next.js site to a shareable URL
              with&nbsp;Vercel.
            </p>
          </a>
        </div>
      </main>
    </>
  )
}
